### PR TITLE
Add Mixpanel People API

### PR DESCRIPTION
**Pull request by ksm**
I've been using your client for a few months now, and needed to add support for [Mixpanel's People API](https://mixpanel.com/help/reference/http#people-analytics-updates).

Some things I did:
- bumped DVR to the newest version
- re-recorded existing test cassettes as DVR couldn't find the previous ones (please clone this branch and double check the tests pass for you!)
- wrote one test for the people API
- gently refactored the `track()` function to match it to the newly added `people()`
- I only needed support for the people API `$set` and `$add` profile operations, but I ended up adding support for all operations listed by Mixpanel's docs (they could probably use more tests)

Please let me know if you need any corrections. I did not make any breaking API changes. I tried to make the usage of the `people()` API similar to Mixpanel's official library. E.g.:

``` Objective-C
// Mixpanel's official library (Objective-C)
[mixpanel.people set:@{@"Plan": @"Premium"}];
```

``` Swift
// This library (Swift)
mixpanel.people(.Set(["Plan": "Premium"]))
```

### CODE REVIEW

**Comment by soffes** [comment]
How do you feel about moving `track` to a new `Analytics` struct and moving your enum to methods on a `People` struct?

``` swift
import Mixpanel

Mixpanel.identify("hi")

Analytics.track("foo")
People.set(["Plan": "Premium"])
```

**Comment by ksm** [comment]
I'm not a fan of `Analytics` and `People` being separate from `Mixpanel`. I would prefer:

``` Swift
import Mixpanel

Mixpanel.identify("hi")

Mixpanel.analytics.track("foo")
Mixpanel.people.set(["Plan": "Premium"])
```

or even (this would make it very similar to the official lib):

``` Swift
import Mixpanel

Mixpanel.identify("hi")

Mixpanel.track("foo")
Mixpanel.people.set(["Plan": "Premium"])
```

**Comment by soffes** [comment]
What do you think @calebd & @hyperspacemark?

**Comment by calebd** [comment]
It doesn't really bother me. Both `People` and `Analytics` would still be under the `Mixpanel` module namespace. I think the only real downside is finding the API while writing code.

**Comment by soffes** [comment]
Right because you can write `Mixpanel.Analytics.track` or `Analytics.track`. Either way, I'm not a fan of the enum.

Thanks so much for your work on this @ksm! Just need to nail down an API we're happy with though. Any thoughts?

**Comment by ksm** [comment]
I don't have strong opinions on the API for tracking events or updating the user's profile. The enum that's in the PR is something I arrived at, because I wanted to keep `Mixpanel`'s API to only two methods: `track()` and `people()`.

I have an `Analytics` struct in my project and if we add `Analytics` here then they will conflict. Yes, it'll be namespaced under the `Mixpanel` module, so the project will build fine, but if you try to use the Mixpanel `Analytics` struct from within the project `Analytics` struct then Swift won't see it. Please let me know if there are sensible workarounds or something I'm unaware of.

**Pull request closed without merging**
